# 1 = refresh all players every tick, 2 = every 2 ticks, 3 = every 3 ticks and so on
tick-rate: 1
fish-player:
  # Should the players who are marked as fish be able to breath in non-fish worlds on only in fish worlds?
  only-in-fish-worlds: true
  # This makes all players who don't have a direct flag associated to them a fish when it is set to true
  players-are-fish-by-default: false
fish-worlds:
  # All players who are in a fish-world should be fish or only those who were marked as fish by command or plugin?
  all-players-are-fish: true
  # If you want all your worlds to become fish-world, set this to true
  all: false
  # If you want to disable this plugin in all nether dimensions, set this to true
  not-nether: true
  # This is a list of strings, you can add the name of the worlds here
  by-name:
    - world
  # This is a list of regular expressions, this is an advanced way just in case you want to be fancy
  regex: []
