# Required
# The final name of your plugin, other plugins may use this name to declare dependency on your plugin
name: FishMode

# Required
# The name of your class file that overrides PluginBase
main: org.powernukkit.plugins.fishmode.FishModePlugin

version: "${project.version}"

api: ["1.0.13"]

load: POSTWORLD

author: joserobjr

description: This plugin was made to address a plugin request where the players should breathe in water and suffocate for lack of oxygen in air, like a fish.
website: https://github.com/PowerNukkit/FishMode-Plugin

depend:
 - PowerNukkit
 
commands:
 setfish:
  description: Set a direct fish flag to a player
  usage: "/setfish [true] [Player Name]"
  permission: fishmode.cmd.setfish
 unsetfish:
  description: Remove the direct fish flag from a player
  usage: "/unsetfish [Player Name]"
  permission: fishmode.cmd.unsetfish
 fishmode-reload:
  description: Reload the configs from the filesystem
  usage: "/reload-fishmode"
  permission: fishmode.cmd.fishmode-reload
 isfish:
  description: Shows the fish status of a player
  usage: "/isfish [Player Name]"
  permission: fishmode.cmd.isfish
    
permissions:
 fishmode.cmd.*:
  description: "Gives access to all FishMode commands"
  default: op
  children:
   fishmode.cmd.setfish: true
   fishmode.cmd.unsetfish: true
   fishmode.cmd.fishmode-reload: true
   fishmode.cmd.isfish: true

 fishmode.cmd.setfish:
  description: "Allows the user to run the /setfish command"
  default: op
 fishmode.cmd.unsetfish:
  description: "Allows the user to run the /unsetfish command"
  default: op
 fishmode.cmd.fishmode-reload:
  description: "Allows the user to run the /fishmode-reload command"
  default: op
 fishmode.cmd.isfish:
  description: "Allows the user to run the /isfish command"
  default: op
 fishmode.fish.never:
  description: "Makes the user never fish, most settings except the direct fish flag, this has priority over fishmode.fish.always"
  default: false
 fishmode.fish.always:
  description: "Makes the user always fish unless directly set to not be"
  default: false
